name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Azure Static Web Apps Deploy
    steps:
      - uses: actions/checkout@v3

      - name: Deploy App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_2 }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "."
